### ISSUE TITLE
jProf & DevZen

### ISSUE THREAD

**Issue by aliaksei-lithium** [JavaBy/Community#12]
## Текст анонса

Привет! 
Мы приготовили вам сюрприз! Светлана из подкаста DevZen приезжает в Минск и будет рада встретиться со слушателями, поделиться рассказами про жизнь IT-стартапов в сердце Великобритании, а также про особенности подкастинга в рунете. 

По сему, DevZen совместно с Java Professionals BY организуют неформальную встречу уже в эту пятницу, 23 июня, 19:00 в SPACE. Заинтригованы?

Света затронет следующие темы:

* повседневная жизнь в Великобритании
* имеет ли смысл переезжать в Великобританию, чтобы делать свой стартап
* чего ожидают инвесторы от фаундеров
* на что обратить внимание при чтении term sheet
* помогают ли акселераторы стартапам
* как выглядит жизнь внутри в Entrepreneur First, лучшем стартап-акселераторе по версии The Europas 2017
* удачи и провалы в жизни стартапов
* как меняется мировоззрение инженера при переходе на роль фаундера
* будут ли в DevZen еще выпуски про предпринимательство
* ответы на ваши неудобные вопросы.
Приходите!

В ожидании встречи можете послушать выпуски DevZen, где Света уже частично раскрывала тему: 
http://devzen.ru/episode-0133/
 http://devzen.ru/episode-0136/

## Подготовка

Смотрящий за встречей – Aliaksei Zh.

- [x] Забронировать дату в Space (23 мая)
- [x] Открыть форму регистрации (timepad)
- [x] Подготовить swag (jprof, devzen)
- [x] Написать анонс 
- [x] Опубликовать анонс на [jprof.by](https://jprof.by/), facebook, vk

## Пред-митап

- [x] Подготовить вступительную речь
- [x] Уточнить меню кофе-паузы

## Митап

- [x] Разложить стикеры
- [x] Выставить роллапы
- [x] Активности на митапе, модерация

## Пост-митап

- [x] Провести опрос
- [x] Написать отчет на сайт
- [x] Ссылку на отчет и опрос отправить в рассылку на зарегистрированных участников

**Comment by SBozhko** [comment]
Привет! 

Мы приготовили вам сюрприз! Светлана из подкаста DevZen приезжает в Минск и будет рада встретиться со слушателями, поделиться рассказами про жизнь IT-стартапов в сердце Великобритании, а также про особенности подкастинга в рунете. 

По сему, DevZen совместно с Java Professionals BY организуют неформальную встречу уже в эту пятницу, 23 июня, 19:00 в SPACE. Заинтригованы? 

Света затронет следующие темы:
- повседневная жизнь в Великобритании 
- имеет ли смысл переезжать в Великобританию, чтобы делать свой стартап
- чего ожидают инвесторы от фаундеров 
- на что обратить внимание при чтении term sheet 
- помогают ли акселераторы стартапам 
- как выглядит жизнь внутри в Entrepreneur First, лучшем стартап-акселераторе по версии The Europas 2017
- удачи и провалы в жизни стартапов 
- как меняется мировоззрение инженера при переходе на роль фаундера 
- будут ли в DevZen еще выпуски про предпринимательство
- ответы на ваши неудобные вопросы.

Приходите!

В ожидании встречи можете послушать выпуски DevZen, где Света уже частично раскрывала тему: 
http://devzen.ru/episode-0133/
 http://devzen.ru/episode-0136/

**Comment by SBozhko** [comment]
Если будешь печатать swag, то можно еще и devzen стикеров напечатать, а то у меня мало.
