### ISSUE TITLE
Описать процесс принятия решений в сообществе

### ISSUE THREAD

**Issue by IRus** [JavaBy/Community#3]
- [ ] Предложение изменений в документы
- [ ] Сетап митапов

**Comment by aliaksei-lithium** [comment]
Сетап митапов
---
Перед каждым мероприятием создаётся *.md файл формата `<event-name>-<date].md` где описываем что будет, когда, кто присутствует/приглашён, ссылки на мероприятие в интернете и регистрацию. Документ редактируется по мере появления новых деталей, а так же при изменениях через PR.  Мелкие правки, такие как опечатки, неточности, исправление неправильных ссылок, можно менять прямым редактированием. 
Пример: https://github.com/JavaBy/Community/blob/master/events/Coffee%20And%20Code%20(Dec%202016).md
https://github.com/JavaBy/Community/blob/master/events/jProf%20meetup%2022-12-2016.md

**Comment by aliaksei-lithium** [comment]
Предложение изменений в документы
---
Каждый документ создаётся рабочей группой из одного или нескольких человек.
Перед началом работ, рабочая группа сообщает об этом. Каждый член орг. группы может узнать текущий статус работы над документом.
После того как документ доходит до стадии публикации(даже если он не полностью закончен, но рабочая группа пожелала открыть документ) – публикуется в GitHub и рассылается ссылка на ревью членам орг комитета. Ревью, правки, голосования – через  PR. Однако создатель PR должен контролировать что бы его PR был принят во внимание и должным образом обработан.
