### ISSUE TITLE
Post Meetup #12

### ISSUE THREAD

**Issue by IRus** [JavaBy/Community#6]
- [x] Отправить видео Леши на монтаж
    - [x] Скинуть видео Руслану для конвертации
    - [x] Скинуть видео оператору
- [x] Сделать форму для отзывов
- [x] Собрать все фото с митапа, отобрать фото в отчет
- [x] Написать письмо с ссылками, призывом написать отзыв, ...
- [x] Написать отчет на сайт

**Comment by aliaksei-lithium** [comment]
Скинул видео Руслану.
Сделал форму отзыва https://goo.gl/forms/WV7kUeR13wWURyjr1

**Comment by aliaksei-lithium** [comment]
All done
