### ISSUE TITLE
Новые майки для сообщества

### ISSUE THREAD

**Issue by aliaksei-lithium** [JavaBy/Community#7]
Для нового лого, нужно сделать и новые майки, которые будем раздавать спикерам, и как призы. 

**Цвет**: серый/чёрный
**Кол-во**: всего 20 штук, размеры
* 3 S
* 12 M (6 из них принт а5 формата слева)
* 5 L (2 из них принт а5 формата слева)

**Принт**: цветной. Всё по центру формат a4. Кроме нескольких штук а5 (слева на груди). Надпись сзади - по центру сверху.

Исходники (ВПЕРЕДИ: а4/a5 _front.eps_ и СЗАДИ: _back.eps_) https://drive.google.com/open?id=0B1WEm8IKzIa9YkVSZmo0MUVhOGc

Предварительный исполнитель: http://www.simtex.by

**Comment by aliaksei-lithium** [comment]
Плюс как обсудили в часике, ещё несколько маек для членов сообщества.
Отпишитесь реплаем кому делать и размер.

**Comment by IRus** [comment]
+1 серая размер L

**Comment by aliaksei-lithium** [comment]
+1 тёмно-синий цвет || размер M

**Comment by IRus** [comment]
Андрей: серая xl

**Comment by bsiamionau** [comment]
темный цвет, по приоритету: xl, xxl, l

**Comment by IRus** [comment]
Пока получается такой список: 
3 x S  - темно серые, принт по центру формат а4
6 x М  - темно серые, принт по центру формат а4
7 x М  - темно серые, принт слева формат а5
2 x L   - темно серые, принт слева формат а5
3 x L   - темно серые, принт по центру формат а4
2 x XL - темно серые, принт слева формат а5
1 x M  - темно синия, принт слева формат а5

**Comment by IRus** [comment]
Заказ сделан и оплачен, сумма 302.40BYN
